override GARVERSION ?= 1.9.15
override MASTER_SITES = $(MASTER_GNU_ALPHA)
override MASTER_SUBDIR = guile/
override LIBDEPS = gc gmp libtool readline libunistring libffi

SIGFILES = $(DISTFILES).sig

include ../../gnu/guile/Makefile


