override GARVERSION ?= 5.7.98
override MASTER_SITES = $(MASTER_GNU_ALPHA)
override MASTER_SUBDIR = rcs/

SIGFILES = $(DISTFILES).sig

CONFIGURE_OPTS = RCS_PRETEST=acknowledged

include ../../gnu/rcs/Makefile


