# Copyright © 2013 Brandon Invergo <brandon@invergo.net>
#
# This file is part of GSRC.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.

NAME = Talk Filters
GARNAME = talkfilters
GARVERSION = 2.3.8
HOME_URL = http://www.gnu.org/software/talkfilters/
DESCRIPTION = Convert English text to humorous dialects
define BLURB
The GNU Talk Filters are programs that convert English text into
stereotyped or otherwise humorous dialects.  The filters are provided
as a C library, so they can easily be integrated into other programs.
endef

######################################################################

MASTER_SITES = http://www.hyperrealm.com/
MASTER_SUBDIR = $(GARNAME)/
DISTFILES = $(DISTNAME).tar.gz
SIGFILES =

BUILDDEPS =
LIBDEPS =

######################################################################

include ../../gar.lib/auto.mk
include ../../gar.lib/info.mk
include config.mk
