# Copyright © 2013 Brandon Invergo <brandon@invergo.net>
#
# This file is part of GSRC.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.

NAME = Renaissance
GARNAME = renaissance
UPSTREAMNAME = Renaissance
GARVERSION = 0.9.0
HOME_URL = http://www.gnustep.it/Renaissance/
DESCRIPTION = An XML-based GUI-design system

######################################################################

MASTER_SITES = http://www.gnustep.it/
MASTER_SUBDIR = $(UPSTREAMNAME)/Download/
DISTFILES = $(DISTNAME).tar.gz
SIGFILES = 
CONFIGURE_SCRIPTS =

BUILDDEPS =
LIBDEPS = gnustep-make gnustep-base

######################################################################

include ../../gar.lib/gnustep.mk
include config.mk
